CREATE TABLE pessoa(
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	LOGRADOURO VARCHAR(300),
	NUMERO VARCHAR(10),
	COMPLEMENTO VARCHAR(50),
	BAIRRO VARCHAR(100),
	CEP VARCHAR(8),
	CIDADE VARCHAR(80),
	ESTADO VARCHAR(2),
	ATIVO BOOLEAN	
)ENGINE=InnoDB CHARSET=utf8;

