CREATE TABLE lancamento(
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	DATA_PAGAMENTO DATE,
	VALOR DECIMAL(10, 2) NOT NULL,
	OBSERVACAO VARCHAR(100),
	TIPO VARCHAR(20),
	FK_CATEGORIA BIGINT(20),
	FK_PESSOA BIGINT(20),
	FOREIGN KEY (FK_CATEGORIA) REFERENCES categoria(ID),
	FOREIGN KEY (FK_PESSOA) REFERENCES pessoa(ID)
)ENGINE=InnoDB CHARSET=utf8;


