CREATE TABLE usuario (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(400) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE permissao (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE usuario_permissao (
	USUARIO_ID BIGINT(20) NOT NULL,
	PERMISSAO_ID BIGINT(20) NOT NULL,
	PRIMARY KEY (USUARIO_ID, PERMISSAO_ID),
	FOREIGN KEY (USUARIO_ID) REFERENCES usuario(ID),
	FOREIGN KEY (PERMISSAO_ID) REFERENCES permissao(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO usuario (NOME, EMAIL, SENHA) VALUES ('Administrador', 'admin@admin.com', '$2a$10$UN0JLADMdDop0KuyYiCVeebLj8R5klMIOO.g7p6EGZGekFnDGtY6K');
INSERT INTO usuario (NOME, EMAIL, SENHA) VALUES ('Simples', 'usuario@usuario.com', '$2a$10$UN0JLADMdDop0KuyYiCVeebLj8R5klMIOO.g7p6EGZGekFnDGtY6K');

INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_CADASTRAR_CATEGORIA');
INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_PESQUISAR_CATEGORIA');
INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_REMOVER_CATEGORIA');

INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_CADASTRAR_PESSOA');
INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_PESQUISAR_PESSOA');
INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_REMOVER_PESSOA');

INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_CADASTRAR_LANCAMENTO');
INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_PESQUISAR_LANCAMENTO');
INSERT INTO permissao (DESCRICAO) VALUES ('ROLE_REMOVER_LANCAMENTO');

-- ADMIN
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 1);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 2);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 3);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 4);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 5);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 6);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 7);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 8);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (1, 9);
-- USUÁRIO COMUM
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (2, 1);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (2, 2);
INSERT INTO usuario_permissao (USUARIO_ID, PERMISSAO_ID) VALUES (2, 3);
